name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM, and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build  

      - name: Package Electron app
        run: |
          yarn electron:package:win
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}  # You can customize the tag name if needed
          release_name: Release ${{ github.run_number }}  # Customize the release name as per your needs
          body: |
            Release ${{ github.run_number }} of your Electron app.  
          draft: false
          prerelease: false
